<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<UserSecretsId>c5a12e2e-2f47-4a0b-8f9f-2a0d0b6c1a01</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\CloudLogin.Web\CloudLogin.Web.csproj" />
	</ItemGroup>

</Project>
