<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\CloudLogin.API\CloudLogin.API.csproj" />
		<ProjectReference Include="..\..\CloudLogin.WebAssembly\CloudLogin.WebAssembly.csproj" />
	</ItemGroup>

<ItemGroup><EmbeddedResource Include="../../docs/**/*.md" LogicalName="WorkshopGuide.%(Filename).md" /><EmbeddedResource Include="../../README.md" LogicalName="WorkshopGuide.overview.md" /><EmbeddedResource Include="../../providers.md" LogicalName="WorkshopGuide.providers.md" /><EmbeddedResource Include="../../Integration.md" LogicalName="WorkshopGuide.integration.md" /></ItemGroup>
  <ItemGroup><ProjectReference Include="../../../CloudCommon/CloudCommon.Theming.Blazor/CloudCommon.Theming.Blazor.csproj" /></ItemGroup>
</Project>
